var dir_51a7f018002b58388f9aee59dffc4461 =
[
    [ "block.c", "block_8c.html", "block_8c" ],
    [ "block.h", "block_8h.html", "block_8h" ],
    [ "ide.c", "ide_8c.html", "ide_8c" ],
    [ "ide.h", "ide_8h.html", "ide_8h" ],
    [ "input.c", "input_8c.html", "input_8c" ],
    [ "input.h", "input_8h.html", "input_8h" ],
    [ "intq.c", "intq_8c.html", "intq_8c" ],
    [ "intq.h", "intq_8h.html", "intq_8h" ],
    [ "kbd.c", "kbd_8c.html", "kbd_8c" ],
    [ "kbd.h", "kbd_8h.html", "kbd_8h" ],
    [ "partition.c", "partition_8c.html", "partition_8c" ],
    [ "partition.h", "partition_8h.html", "partition_8h" ],
    [ "pit.c", "pit_8c.html", "pit_8c" ],
    [ "pit.h", "pit_8h.html", "pit_8h" ],
    [ "rtc.c", "rtc_8c.html", "rtc_8c" ],
    [ "rtc.h", "rtc_8h.html", "rtc_8h" ],
    [ "serial.c", "serial_8c.html", "serial_8c" ],
    [ "serial.h", "serial_8h.html", "serial_8h" ],
    [ "shutdown.c", "shutdown_8c.html", "shutdown_8c" ],
    [ "shutdown.h", "shutdown_8h.html", "shutdown_8h" ],
    [ "speaker.c", "speaker_8c.html", "speaker_8c" ],
    [ "speaker.h", "speaker_8h.html", "speaker_8h" ],
    [ "timer.c", "timer_8c.html", "timer_8c" ],
    [ "timer.h", "timer_8h.html", "timer_8h" ],
    [ "vga.c", "vga_8c.html", "vga_8c" ],
    [ "vga.h", "vga_8h.html", "vga_8h" ]
];