var dir_4b926564148d66ba432939d02e6f6d03 =
[
    [ "alarm-negative.c", "alarm-negative_8c.html", "alarm-negative_8c" ],
    [ "alarm-priority.c", "alarm-priority_8c.html", "alarm-priority_8c" ],
    [ "alarm-simultaneous.c", "alarm-simultaneous_8c.html", "alarm-simultaneous_8c" ],
    [ "alarm-wait.c", "alarm-wait_8c.html", "alarm-wait_8c" ],
    [ "alarm-zero.c", "alarm-zero_8c.html", "alarm-zero_8c" ],
    [ "mlfqs-block.c", "mlfqs-block_8c.html", "mlfqs-block_8c" ],
    [ "mlfqs-fair.c", "mlfqs-fair_8c.html", "mlfqs-fair_8c" ],
    [ "mlfqs-load-1.c", "mlfqs-load-1_8c.html", "mlfqs-load-1_8c" ],
    [ "mlfqs-load-60.c", "mlfqs-load-60_8c.html", "mlfqs-load-60_8c" ],
    [ "mlfqs-load-avg.c", "mlfqs-load-avg_8c.html", "mlfqs-load-avg_8c" ],
    [ "mlfqs-recent-1.c", "mlfqs-recent-1_8c.html", "mlfqs-recent-1_8c" ],
    [ "priority-change.c", "priority-change_8c.html", "priority-change_8c" ],
    [ "priority-condvar.c", "priority-condvar_8c.html", "priority-condvar_8c" ],
    [ "priority-donate-chain.c", "priority-donate-chain_8c.html", "priority-donate-chain_8c" ],
    [ "priority-donate-lower.c", "priority-donate-lower_8c.html", "priority-donate-lower_8c" ],
    [ "priority-donate-multiple.c", "priority-donate-multiple_8c.html", "priority-donate-multiple_8c" ],
    [ "priority-donate-multiple2.c", "priority-donate-multiple2_8c.html", "priority-donate-multiple2_8c" ],
    [ "priority-donate-nest.c", "priority-donate-nest_8c.html", "priority-donate-nest_8c" ],
    [ "priority-donate-one.c", "priority-donate-one_8c.html", "priority-donate-one_8c" ],
    [ "priority-donate-sema.c", "priority-donate-sema_8c.html", "priority-donate-sema_8c" ],
    [ "priority-fifo.c", "priority-fifo_8c.html", "priority-fifo_8c" ],
    [ "priority-preempt.c", "priority-preempt_8c.html", "priority-preempt_8c" ],
    [ "priority-sema.c", "priority-sema_8c.html", "priority-sema_8c" ],
    [ "tests.c", "tests_8c.html", "tests_8c" ],
    [ "tests.h", "tests_8h.html", "tests_8h" ]
];